const countryName = {
  US: "United States of America",
  IN: "India",
  GB: "United Kingdom",
  EU: "European Union",
  JP: "Japan",
  CA: "Canada",
  AU: "Australia",
  CN: "China",
  RU: "Russia",
  BR: "Brazil",
  ZA: "South Africa",
  MX: "Mexico",
  SG: "Singapore",
  AE: "United Arab Emirates",
  CH: "Switzerland",
  SE: "Sweden",
  NO: "Norway",
  NZ: "New Zealand",
  FR: "France",
  DE: "Germany",
  IT: "Italy",
  ES: "Spain",
  KR: "South Korea",
  // Add more countries as needed
}
